apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus3
  name: connector
spec:
  type: NodePort
  ports:
    - name: "30000"
      port: 30000
      targetPort: 30000
      nodePort: 30000
  selector:
    io.kompose.service: nexus3
status:
  loadBalancer: {}
